spring.application.name=puntodeventabackend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/puntodeventadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:mXUIHbLcjqZvEpKMZwJLTjHKqKyqBvgJ}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
