spring.application.name=puntodeventabackend
server.port=${PORT:8080}

DB_URL=jdbc:mysql://ballast.proxy.rlwy.net:39888/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
DB_USER=root
DB_PASSWORD=mXUIHbLcjqZvEpKMZwJLTjHKqKyqBvgJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.initialization-fail-timeout=-1
